export const mantenimientoRoutes = {
  CLIENTE: "cliente",
  PROVEEDOR: "proveedor",
  VENDEDOR: "vendedor",
  TRANSPORTISTA: "transportista",
  MEDICO: "medico",
  USUARIO: "usuario",

  ALMACEN: "almacen",
  LINEA: "linea",
  SUBLINEA: "sublinea",
  MARCA: "marca",
  UNIDADESMEDIDA: "unidadesmedida",
  ENTIDADESBANCARIAS: "entidadesBancarias",
  DEPARTAMENTO: "departamento",
  PROVINCIA: "provincia",
  DISTRITO: "distrito",
  TIPOPAGO: "tipopago",
  TIPOPRODUCTO: "tipoproducto",
  TIPOVENTA: "tipoventa",

  ARTICULO: "articulo",
  FARMACOLOGIA: "farmacologia",
  GRUPOFARMACOLOGICO: "grupofarmacologico",
  PRESENTACIONGENERAL: "presentationgeneral",
  PRECIOMAYORISTA: "preciomayorista",
  LOTE: "lote",
  CONFIGURACIONLOTE: "configuracionlote",

  TIPOCAMBIO: "tipocambio",
  ENTIDADBANCARIA: "entidadbancaria",
  CUENTABANCARIA: "cuentabancaria",
};
